"""
=============================================================================
ThirdLine — Continuous Controls Monitoring (CCM)
=============================================================================

FILE: ccm/monitor.py

WHAT THIS DOES:
    Transforms ThirdLine from a point-in-time audit tool into a continuous
    assurance system. Instead of running audits manually, CCM:

    1. WATCHES for new agent interactions (file system events)
    2. DETECTS when interaction counts cross materiality thresholds
    3. AUTO-TRIGGERS a targeted re-audit of the affected agent
    4. ALERTS if any new findings are detected
    5. SCHEDULES periodic full-fleet audits (configurable interval)

    Banks require ONGOING monitoring, not annual snapshots.
    CCM is the architectural difference between a tool and a platform.

    MONITORING MODES:
    - EventDriven: watches data/interactions/ for new files
    - Scheduled:   runs full fleet audit every N hours
    - Threshold:   triggers when failure rate exceeds threshold
    - Deployment:  triggers when a new agent version is detected

    ALERT CHANNELS (configurable):
    - Console logging (always)
    - Slack webhook (optional)
    - Email (optional)
    - API webhook (optional)

HOW TO RUN:
    python ccm/monitor.py --mode scheduled --interval 24
    python ccm/monitor.py --mode event-driven
    OR: triggered via /api/v1/ccm/start endpoint

INPUT:  data/interactions/ (monitored directory)
OUTPUT: Automatic audit runs → findings → HITL queue
        data/ccm/monitor_log.json
=============================================================================
"""

from __future__ import annotations

import json
import os
import time
import threading
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Callable

import structlog

import sys
sys.path.insert(0, str(Path(__file__).parents[1]))
from config.settings import settings

logger = structlog.get_logger(__name__)


# ── Alert dataclass ────────────────────────────────────────────────────────────
@dataclass
class CCMAlert:
    """Alert generated by CCM when a threshold is crossed or audit completes."""
    alert_id:    str
    alert_type:  str       # "new_finding" | "threshold_exceeded" | "audit_complete" | "agent_deployed"
    severity:    str       # "CRITICAL" | "HIGH" | "INFO"
    agent_id:    str
    message:     str
    timestamp:   str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata:    dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "alert_id":   self.alert_id,
            "alert_type": self.alert_type,
            "severity":   self.severity,
            "agent_id":   self.agent_id,
            "message":    self.message,
            "timestamp":  self.timestamp,
            "metadata":   self.metadata,
        }


# ── CCM state ──────────────────────────────────────────────────────────────────
@dataclass
class CCMState:
    """Persistent state for the CCM monitor."""
    last_full_audit:     str = ""
    last_audit_per_agent: dict = field(default_factory=dict)
    interaction_counts:  dict = field(default_factory=dict)  # agent_id → count at last audit
    alerts:              list = field(default_factory=list)
    total_audits_triggered: int = 0
    is_running:          bool = False

    def to_dict(self) -> dict:
        return {
            "last_full_audit":      self.last_full_audit,
            "last_audit_per_agent": self.last_audit_per_agent,
            "interaction_counts":   self.interaction_counts,
            "alerts":               self.alerts[-50:],   # keep last 50
            "total_audits_triggered": self.total_audits_triggered,
            "is_running":           self.is_running,
        }


class ContinuousControlsMonitor:
    """
    Event-driven and scheduled continuous audit monitor.

    Keeps ThirdLine's audit coverage current without manual intervention.
    Production-equivalent of what a bank's continuous controls monitoring
    system does for traditional controls — now applied to AI agents.
    """

    # Thresholds that trigger a re-audit
    NEW_INTERACTION_THRESHOLD = 20   # re-audit after 20 new interactions
    FAILURE_RATE_THRESHOLD    = 0.15 # re-audit if >15% of recent interactions fail shield
    SCHEDULED_INTERVAL_HOURS  = 24   # full fleet audit every 24 hours

    def __init__(self, on_alert: Callable[[CCMAlert], None] | None = None):
        self._state     = CCMState()
        self._on_alert  = on_alert or self._default_alert_handler
        self._stop_event = threading.Event()
        self._log_dir   = settings.data_dir / "ccm"
        self._log_dir.mkdir(parents=True, exist_ok=True)
        self._state_path = self._log_dir / "monitor_state.json"
        self._load_state()

    # ── Public API ─────────────────────────────────────────────────────────────
    def start_scheduled(self, interval_hours: float = 24):
        """Start scheduled monitoring — full fleet audit every N hours."""
        self._state.is_running = True
        self._save_state()
        logger.info("ccm_scheduled_start", interval_hours=interval_hours)

        def _run():
            while not self._stop_event.is_set():
                self._run_full_audit("scheduled")
                # Wait for interval (check stop every 60 seconds)
                wait_until = time.time() + interval_hours * 3600
                while time.time() < wait_until and not self._stop_event.is_set():
                    time.sleep(60)

        thread = threading.Thread(target=_run, daemon=True, name="ccm-scheduled")
        thread.start()
        return thread

    def start_event_driven(self):
        """Start event-driven monitoring — watch for new interactions."""
        self._state.is_running = True
        self._save_state()
        logger.info("ccm_event_driven_start")

        def _run():
            while not self._stop_event.is_set():
                self._check_interaction_thresholds()
                time.sleep(30)  # check every 30 seconds

        thread = threading.Thread(target=_run, daemon=True, name="ccm-event-driven")
        thread.start()
        return thread

    def trigger_agent_audit(self, agent_id: str, reason: str = "manual") -> dict:
        """
        Trigger a targeted audit of a single agent.
        This is what fires when a new agent version is deployed.
        """
        logger.info("ccm_agent_audit_triggered", agent_id=agent_id, reason=reason)

        # Run the audit
        result = self._run_single_agent_audit(agent_id, reason)

        # Update state
        self._state.last_audit_per_agent[agent_id] = datetime.now(timezone.utc).isoformat()
        self._state.total_audits_triggered += 1

        # Check for new findings and alert
        findings = result.get("findings", [])
        if findings:
            for finding in findings:
                alert = CCMAlert(
                    alert_id   = str(uuid.uuid4()),
                    alert_type = "new_finding",
                    severity   = finding.get("severity", "MEDIUM"),
                    agent_id   = agent_id,
                    message    = f"CCM detected new {finding.get('severity')} finding on {agent_id}: {finding.get('title','')}",
                    metadata   = {"finding_id": finding.get("finding_id"), "dimension": finding.get("dimension"), "reason": reason}
                )
                self._state.alerts.append(alert.to_dict())
                self._on_alert(alert)

        self._save_state()
        return result

    def stop(self):
        """Stop all monitoring threads."""
        self._stop_event.set()
        self._state.is_running = False
        self._save_state()
        logger.info("ccm_stopped")

    def get_status(self) -> dict:
        """Return current CCM status for the API and dashboard."""
        interactions_dir = settings.data_dir / "interactions"
        current_counts   = {}

        if interactions_dir.exists():
            for agent_dir in interactions_dir.iterdir():
                if agent_dir.is_dir():
                    current_counts[agent_dir.name] = len(list(agent_dir.glob("*.json")))

        # Calculate new interactions since last audit per agent
        new_since_audit = {}
        for agent_id, current in current_counts.items():
            last = self._state.interaction_counts.get(agent_id, 0)
            new_since_audit[agent_id] = max(0, current - last)

        return {
            "is_running":              self._state.is_running,
            "total_audits_triggered":  self._state.total_audits_triggered,
            "last_full_audit":         self._state.last_full_audit,
            "last_audit_per_agent":    self._state.last_audit_per_agent,
            "current_interaction_counts": current_counts,
            "new_interactions_since_audit": new_since_audit,
            "recent_alerts":           self._state.alerts[-10:],
            "alert_count":             len(self._state.alerts),
            "thresholds": {
                "new_interaction_trigger": self.NEW_INTERACTION_THRESHOLD,
                "failure_rate_trigger":    self.FAILURE_RATE_THRESHOLD,
                "scheduled_interval_hrs":  self.SCHEDULED_INTERVAL_HOURS,
            }
        }

    # ── Internal methods ────────────────────────────────────────────────────────
    def _check_interaction_thresholds(self):
        """
        Check if any agent has accumulated enough new interactions
        to warrant a re-audit. Called every 30 seconds in event-driven mode.
        """
        interactions_dir = settings.data_dir / "interactions"
        if not interactions_dir.exists():
            return

        for agent_dir in interactions_dir.iterdir():
            if not agent_dir.is_dir():
                continue
            agent_id = agent_dir.name
            current_count = len(list(agent_dir.glob("*.json")))
            last_count    = self._state.interaction_counts.get(agent_id, 0)
            new_count     = current_count - last_count

            if new_count >= self.NEW_INTERACTION_THRESHOLD:
                logger.info("ccm_threshold_reached", agent_id=agent_id, new_interactions=new_count)

                alert = CCMAlert(
                    alert_id   = str(uuid.uuid4()),
                    alert_type = "threshold_exceeded",
                    severity   = "INFO",
                    agent_id   = agent_id,
                    message    = f"CCM: {new_count} new interactions on {agent_id} — triggering re-audit",
                    metadata   = {"new_count": new_count, "threshold": self.NEW_INTERACTION_THRESHOLD}
                )
                self._on_alert(alert)
                self.trigger_agent_audit(agent_id, reason=f"threshold_{new_count}_new_interactions")
                self._state.interaction_counts[agent_id] = current_count

    def _run_full_audit(self, reason: str = "scheduled"):
        """Run a full fleet audit."""
        logger.info("ccm_full_audit_start", reason=reason)
        try:
            from assurance_agents.adk.orchestrator import AuditOrchestrator
            orchestrator = AuditOrchestrator()
            result = orchestrator.run({"agent_id": "all"})
            self._state.last_full_audit = datetime.now(timezone.utc).isoformat()
            self._state.total_audits_triggered += 1

            # Alert on any new critical findings
            for finding in result.findings:
                if finding.get("severity") in ("CRITICAL", "HIGH"):
                    alert = CCMAlert(
                        alert_id   = str(uuid.uuid4()),
                        alert_type = "new_finding",
                        severity   = finding.get("severity", "HIGH"),
                        agent_id   = finding.get("agent_id", ""),
                        message    = f"CCM full audit ({reason}): {finding.get('severity')} finding — {finding.get('title','')}",
                        metadata   = {"finding_id": finding.get("finding_id"), "reason": reason}
                    )
                    self._state.alerts.append(alert.to_dict())
                    self._on_alert(alert)

            alert = CCMAlert(
                alert_id   = str(uuid.uuid4()),
                alert_type = "audit_complete",
                severity   = "INFO",
                agent_id   = "fleet",
                message    = f"CCM full fleet audit complete ({reason}). {result.total_findings} findings. Ledger INTACT.",
                metadata   = {"findings": result.total_findings, "run_id": result.run_id}
            )
            self._state.alerts.append(alert.to_dict())
            self._on_alert(alert)
            self._save_state()
            return result

        except Exception as e:
            logger.error("ccm_full_audit_failed", error=str(e))
            return None

    def _run_single_agent_audit(self, agent_id: str, reason: str) -> dict:
        """Run a targeted audit of one agent."""
        try:
            from assurance_agents.adk.orchestrator import AuditOrchestrator
            orchestrator = AuditOrchestrator()
            result = orchestrator.run({"agent_id": agent_id})
            return {
                "run_id":   result.run_id,
                "agent_id": agent_id,
                "findings": result.findings,
                "status":   result.status,
                "reason":   reason,
            }
        except Exception as e:
            logger.error("ccm_single_audit_failed", agent_id=agent_id, error=str(e))
            return {"run_id": "", "agent_id": agent_id, "findings": [], "status": "FAILED", "reason": reason}

    def _default_alert_handler(self, alert: CCMAlert):
        """Default: log the alert. Override to add Slack/email/webhook."""
        if alert.severity == "CRITICAL":
            logger.warning("ccm_alert_critical", **alert.to_dict())
        elif alert.severity == "HIGH":
            logger.warning("ccm_alert_high", **alert.to_dict())
        else:
            logger.info("ccm_alert", **alert.to_dict())

    def _load_state(self):
        if self._state_path.exists():
            try:
                data = json.loads(self._state_path.read_text())
                self._state.last_full_audit          = data.get("last_full_audit","")
                self._state.last_audit_per_agent     = data.get("last_audit_per_agent",{})
                self._state.interaction_counts       = data.get("interaction_counts",{})
                self._state.alerts                   = data.get("alerts",[])
                self._state.total_audits_triggered   = data.get("total_audits_triggered",0)
                self._state.is_running               = False   # always start stopped
            except Exception:
                pass

    def _save_state(self):
        self._state_path.write_text(json.dumps(self._state.to_dict(), indent=2, default=str))


# ── CLI entry point ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    from rich.console import Console
    from rich.panel import Panel
    from rich.live import Live
    from rich.table import Table
    import time

    console = Console()
    parser = argparse.ArgumentParser(description="ThirdLine CCM Monitor")
    parser.add_argument("--mode", choices=["scheduled","event-driven","status","trigger"], default="status")
    parser.add_argument("--interval", type=float, default=24.0, help="Hours between scheduled audits")
    parser.add_argument("--agent", default="all", help="Agent ID to trigger audit for")
    args = parser.parse_args()

    monitor = ContinuousControlsMonitor()

    if args.mode == "status":
        status = monitor.get_status()
        console.print(Panel.fit(
            f"[bold blue]ThirdLine CCM Status[/bold blue]\n\n"
            f"  Running:        {status['is_running']}\n"
            f"  Total audits:   {status['total_audits_triggered']}\n"
            f"  Last full audit:{status['last_full_audit'] or 'Never'}\n"
            f"  Alert count:    {status['alert_count']}\n\n"
            f"  Interaction counts: {status['current_interaction_counts']}\n"
            f"  New since last audit: {status['new_interactions_since_audit']}",
            border_style="blue"
        ))

    elif args.mode == "trigger":
        console.print(f"[cyan]Triggering audit for: {args.agent}[/cyan]")
        if args.agent == "all":
            monitor._run_full_audit("manual")
        else:
            result = monitor.trigger_agent_audit(args.agent, reason="manual_trigger")
            console.print(f"[green]Audit complete. Findings: {len(result.get('findings',[]))}[/green]")

    elif args.mode in ("scheduled","event-driven"):
        console.print(Panel.fit(
            f"[bold blue]ThirdLine CCM — {args.mode.title()} Mode[/bold blue]\n"
            f"Interval: {args.interval}h | Press Ctrl+C to stop",
            border_style="blue"
        ))
        try:
            if args.mode == "scheduled":
                monitor.start_scheduled(args.interval)
            else:
                monitor.start_event_driven()
            while True:
                time.sleep(10)
                status = monitor.get_status()
                console.print(f"[dim]{datetime.now().strftime('%H:%M:%S')} — CCM running · Audits: {status['total_audits_triggered']} · Alerts: {status['alert_count']}[/dim]")
        except KeyboardInterrupt:
            monitor.stop()
            console.print("\n[yellow]CCM stopped.[/yellow]")
